"""add last_seen to devices

Revision ID: bd48c3279a61
Revises: 47dfeda96709
Create Date: 2026-05-01 08:08:06.649686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd48c3279a61'
down_revision = '47dfeda96709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('field_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('weed_detections', schema=None) as batch_op:
        batch_op.alter_column('grid_x',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grid_y',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weed_detections', schema=None) as batch_op:
        batch_op.alter_column('grid_y',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grid_x',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('field_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
